name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'image Docker
        run: docker build -t devops-projet-app ./app

      - name: Lancer le conteneur
        run: docker run -d -p 5000:5000 --name test-app devops-projet-app

      - name: Attendre que le conteneur démarre
        run: sleep 3

      - name: Tester le endpoint /health
        run: curl --fail http://localhost:5000/health

      - name: Arrêter le conteneur
        run: docker stop test-app
